# Site settings
title:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://chrisport.github.io" # the base hostname & protocol for your site
collections:
  projects:
    output: true
# Build settings
markdown: kramdown
