# Site settings
title: Chrisport
name: Christoph Portmann
description: Coder, Gopher, Katık
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ChristophPort
github_username:  chrisport

# Build settings
markdown: kramdown
