# Site settings
title: Chrisport
email: portmann.christoph@gmail.com
description: Chris Port
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ChristophPort
github_username:  chrisport

# Build settings
markdown: kramdown
